TITLE Anticuchos

{[Beef]

# In a large bowl combine: [3 tbl red wine vinegar], [2 tsp ground hot paprika], [1 tsp salt], [1 tsp freshly ground black pepper], [1/2 tsp ground cumin], [1/2 tsp ground turmeric].
# Trim [1.5 lbs sirloin steak] and cut into half-inch pieces. 
# Add beef to the bowl and mix to coat.
# Cover and chill for an hour.
}

{[Yellow Pepper Sauce]

# Preheat broiler.

# Clean and half [10 oz yellow bell pepper]. Place pepper halves, skin sides up, on a foil-lined baking sheet. Flatten with hand. 

# Broil 15 minutes or until blackened. Place in a covered container. Let stand 10 minutes.

# In a blender combine: [1/2 cup green onions], [2 tbl white vinegar], [1 tbl water], [1 tbl olive oil], [1 tbl lemon juice], [1 tsp ground cumin], [1 tsp ground hot paprika], [1/2 tsp ground turmeric], [1/4 tsp salt], [1/4 tsp freshly ground black pepper], [1 cloves garlic].
 
# Peel and coarsely chop pepper. Add to blender, and process until smooth.

}

{[Fiery rub]
#  [1 tsp ground aji amarillo or hot paprika], [1 tsp salt], [1/2 tsp freshly ground black pepper], [1/4 tsp ground turmeric], [3 tbl chopped fresh flat-leaf parsley].
}

# Prepare grill.
# Remove beef from bowl, discarding marinade. Thread $[beef] onto skewers. Press $[fiery rub] onto $[Beef]. 
# Grill.  
# Serve with Roasted $[Yellow Pepper Sauce].