TITLE Baked Tomato Sauce

# Adjust oven rack to lower position and preheat oven to 300F (165C).

# Place [112 oz whole peeled tomatoes] in a large bowl. Using your hands, crush the tomatoes by squeezing them in your fingers until pieces no larger than 1/2-inch remain. Transfer 3 cups of crushed tomatoes to a sealed container and reserve in the refrigerator until step 4.

# Heat [0.25 cup extra-virgin olive oil] and [4 tbl butter] over medium heat in a large Dutch oven until butter is melted. Add [8 cloves garlic], minced and cook, stirring, until softened and fragrant but not browned, about 2 minutes.

# Add [1 tsp red pepper flakes] and [1 tbl dried oregano] and cook, stirring, until fragrant, about 1 minute.

# Add tomatoes, [1 item medium carrot] cut into large chunks, [1 item medium onion] split in half, and [1 item large stem fresh basil]. Stir to combine. Season lightly with salt and pepper. Bring to a simmer over high heat.

# Cover Dutch oven with lid slightly ajar and transfer to oven. Cook, stirring once every 1 to 2 hours, until reduced by about half and darkened to a deep red, 5 to 6 hours (reduce oven temperature if the sauce is bubbling too rapidly or the browned bits begin to turn too dark).

# Remove from oven. Using tongs, discard onion halves, carrots, and basil stems.

# Add reserved tomatoes to sauce and stir to combine. Add [1 tbl fish sauce], if using. Season generously with salt and pepper and stir in [1/2 cup basil], minced along with additional olive oil as desired.

* https://www.seriouseats.com/the-best-slow-cooked-italian-american-tomato-sauce-red-sauce-recipe

* Active: 20 mins
* Total: 6 hrs
* Serves: 6 to 8 servings
* Makes: 2 quarts
