TITLE Momofuku's Bo Ssam Recipe

{[Pork Butt]
# Place the [1 item bone-in pork butt] in a large, shallow bowl. Mix [1 cup white sugar] and   [1 cup kosher salt] together in another bowl, then rub the mixture all over the meat. Cover it with plastic wrap and place in the refrigerator for at least 6 hours, or overnight.
# When you're ready to cook, heat oven to 300F. Remove pork from refrigerator, brush any excess sugar mixture off the fat cap and discard any juices. Place the pork in a roasting pan and set in the oven and cook for approximately 6 hours, or until it collapses, yielding easily to the tines of a fork. (After the first hour, baste hourly with pan juices.) At this point, you may remove the meat from the oven and allow it to rest for up to an hour.
}

{[Ginger-Scallion Sauce]
# Stir together [2.5 cup scallions] thinly sliced, [1/2 cup [minced] ginger], [1/4 cup neutral oil], [1.5 tsp light soy sauce], [3/4 tsp sherry vinegar], [salt] to taste.
}

{[Ssam Sauce]
# Strig together [2 tbl ssamjang], [1 tbl cochujang], [1 tbl sherry vinegar], and [1 tbl neutral oil].
}
{[Accompaniments]
# Prepare [2 cup white rice], wash [3 head bibb lettuce] and separate leaves. Put [Kimchi] and sauces into serving bowls.
}

# When your $[Accompaniments] are prepared and you are ready to serve the food, turn oven to 500F. Rub  [7 tbl brown sugar] all over the cooked pork. Place in oven for approximately 10 to 15 minutes, or until a dark caramel crust has developed on the meat. Serve hot, with the accompaniments.

* Consider scaling down the salt sugar mixture, resulting pork was excellent but we might like it better with a bit less salt.

* Ssam sauce has been modified by reducing the oil and vinegar.
