TITLE Buttermilk Beans, Greens, and Eggs

# Prep [1 item yellow onion[, thinly sliced]] and [5 cloves garlic[, minced]]. 
In a medium to large saucepan heat [olive oil] over medium heat. Add [5 sprig thyme] and fry until fragrant, about 1 minute.
# Add onion and garlic; reduce the heat to low and sweat until tender.
# Add [1/2 lbs dried white beans] and enough water to cover by 2 inches. 
# Simmer until the beans are completely tender and creamy and the water is mostly absorbed, 45 to 75 minutes.
# Off the heat, stir into the beans combine:{ [5 cloves garlic[, minced]] [2 tsp [kosher] salt] [2 cup buttermilk] }
# Cover and chill in the fridge at least 30 minutes, ideally overnight.
# Before serving, remove the thyme sprigs and gently warm the beans over low heat.
# Prep [2 head kale] by washing and cutting into ribbons.
# Saute kale with [olive oil] and [salt] until bright in color and starting to soften.
# Add [1/2 cup white wine] and [1/4 tsp allepo]. Let the wine evaporate by roughly half.
# Fry [eggs] (or preparation of your choosing).
# Dish the beans into bowls, nestle a scoop of greens and an egg on top.
