TITLE Chickpea Pancakes With Greens and Cheese

* Serves 2

{[Batter]
# In a medium bowl whisk together: [1/2 cup chickpea flour], [10 tbl water], [1 tbl oil]. Let stand for 15 minutes to an hour to hydrate the flour.
}

# Preheat oven to 350 F. 

# Saute [1/2 item red onion[, thinly sliced]] until softened. 
# Add [1 cup brussels sprouts[, thinly sliced]] and [4 cloves garlic[, minced]] and saute until lightly browned.
# Add [1 head tuscan kale[, thinly sliced]] and saute until tender
# Season with [salt] and [2 tsp hot sauce]. Keep warm

# In a non-stick skillet hest [1 tsp oil]
# Pour [1/4 cup $[batter]] into center of skillet and swirl to form a thin pancake. 
# Cook until well browned underneath and crispy around edges. Flip pancake and cook just until second side is lightly browned. 
# Transfer to a rimmed baking sheet. Repeat process with remaining batter 
# Divide vegetables between half of the pancakes and top with [4 oz cheddar cheese] and remaining remaining pancakes. 
# Bake until cheese is melted. 
# Serve with [yogurt] and [hot sauce].