TITLE Chicken Chile Verde

{[prep'd veg]
# Seed and roughly chop [2 item Serrano or jalapeno peppers], [1 lbs poblano peppers] and [6 oz Anaheim or Cubanelle peppers]
# Husk and quater [12 oz tomatillos]
# Roughly chop [10 oz white onion]
}
{[chile]
# Combine [3 lbs bone-in, skin-on chicken thighs and drumsticks],  $[prep'd veg], [6 cloves garlic], [1 tbl whole cumin seeds], toasted and ground, and a big pinch of [salt] in a pressure cooker.

# Heat over high heat until gently sizzling, then seal pressure cooker, bring to high pressure, and cook for 15 minutes. Release pressure.

# Using tongs, transfer chicken pieces to a bowl and set aside.

# Add [1/2 cup fresh cilantro leaves] and [1 tbl Asian Fish Sauce] to remaining contents of pressure cooker.

# Blend with an immersion blender or in a countertop blender and season to taste with [salt].

# Return chicken to sauce, discarding skin and bones and shredding if desired.

# Transfer to a serving platter, garnish with chopped cilantro, and serve immediately with [fresh corn tortillas] and [lime wedges].
}

LINK https://www.seriouseats.com/pressure-cooker-fast-and-easy-chicken-chile-verde-recipe
* Active: 10 mins
* Total: 30 mins
* Serves: 4 to 6 servings
