TITLE Grilled Chicken and Roasted Red Pepper Sandwiches with Fontina Cheese

# Flatten [1 lbs boneless skinless chicken breasts] between 2 sheets of heavy-duty plastic wrap, and pound to 3/4-inch thickness using a meat mallet or rolling pin.

# Combine [1 tbl lemon juice], [1 tbl dijon mustard], [2 tsp olive oil], [1/4 tsp dried thyme], [1 cloves garlic], and chicken in a large zip-top plastic bag; seal. Marinate in refrigerator 2 hours, turning occasionally.

# Prepare grill to medium-high heat.

# Saute [1 cup vertically sliced onion] until they soften slightly. Add [4 cloves garlic], [1 tsp sugar], [3/4 tsp fennel seeds, crushed,] [1/4 tsp crushed red pepper], [1/4 tsp salt], [1/4 tsp black pepper], [7 oz roasted red bell peppers]. Cook until onions are tender. Stir in [1 tbl red wine vinegar] and remove from heat.

# Remove chicken from bag; discard marinade. Grill chicken. Cool slightly and slice.

# Slice [1 item loaf focaccia] horizontally. Stack with [3 oz fontina cheese], thinly sliced. Arrange chicken and pepper mixture over cheese. Top with top half of bread; press lightly.
