TITLE Chili Cheese Black Bean Enchiladas


# Preheat oven to 350F.
# Heat a large nonstick skillet coated with cooking spray over medium-high heat. Add [1/2 cup chopped onion] saute until tender.
# Stir in [1/2 tsp ground cumin], [1/2 tsp dried oregano], [1/2 tsp chili powder], [2 cloves garlic [minced]], [15 oz black beans[, rinsed and drained]], and [12 oz frozen soy crumbles[, thawed]].
# Cook 2 minutes, stirring mixture frequently.
# Stir in [3/4 cup bottled salsa], and cook 1 minute. Remove from heat, and add [3 oz cream cheese[, softened]] and [2 oz [shredded] extra sharp cheddar cheese] stirring until cheese melts.
# Spread [1/2 cup enchilada sauce] in bottom of a 13 x 9-inch baking dish coated with cooking spray.
# [12 item corn tortillas] - Working individually warm tortillas according to package directions. Spoon about 1/3 cup black bean mixture down center of each tortilla, and roll up. Arrange enchiladas, seam sides down, crosswise in dish.
# Pour [3/4 cup enchilada sauce] sauce evenly over enchiladas, and sprinkle with 1/2 cup cheddar.
# Bake minutes or until thoroughly heated.
