TITLE Corn Chowder

# Remove the kernels from [6 item ears of corn]. Reserve both the kernels and the cobs. 
# Use the back of a knife to scrape corn cobs into a medium saucepan to collect any milk left in the bases of the kernels. 
# Break corn cobs in half and add to saucepan. 
# Add [6 cup chicken stock], [1 item bay leaf], [1 tsp fennel seed], and [1 tsp black peppercorns]. Stir to combine. 
# Bring to a boil over high heat, reduce to just below a simmer, and let steep for 10 minutes. 
# Strain through a fine mesh strainer and discard cobs and spices.

# Finely dice [1 item onion] and mince [2 cloves garlic].
# While stock infuses, melt [4 tbl butter] in a separate 3 quart saucepan over medium-high heat. Add onion, garlic, and corn kernels, and cook, stirring frequently, until onions are softened and kernels are tender. Reduce heat if butter begins to brown. 
# Add [3 tbl flour] and cook, stirring constantly, for 1 minute.
# Stirring constantly, gradually add infused corn stock, letting mixture come to a simmer. 
# Add [1.5 cup russet potato[, half inch dice]].
# Let simmer, stirring occasionally until the potatoes are tender. 
# Add [1 cup half-and-half]. Stir to combine. 
* Soup may look broken with melted butter floating on top at this stage.
# Transfer 1/4 of soup to a blender and blend on high until smooth. 
# Return to pot and whisk to combine. 
# Season to taste with salt, pepper, and sugar. 
# Serve immediately, sprinkled with [3 item scallions [sliced]].