TITLE Crispy Tofu With Cashews and Blistered Snap Peas


* Tofu may be browned either on the stove or in the oven depending on your preference.

{ [Mis en place]
# Press [14 oz extra firm tofu].
# Trim [12 oz snap peas]. 
# Grate [ 2 tbl ginger] and [2 cloves garlic].
# Toast and chop [1/2 cup cashew nuts]
# In a small prep bowl combine:{
[1 tbl soy sauce]
[2 tsp molasses]
}
# Slice [4 item scallion] and [1/4 cup mint].
}

# Preheat oven to 400 degrees if baking the tofu. 
# Prepare [rice] if desired.

# Slice the tofu in half horizontally and cut into 1 inch pieces. Toss with [1 tbl oil].  Season with [salt] and [pepper].
# Place tofu on a rimmed baking sheet and bake until lightly crisp (or pan fry if desired). 
# In a heavy skillet heat [1 tbl oil], add snap peas. Cook, stirring occasionally, until blistered and just tender. Season with salt and remove to a bowl.
# Heat [1 tbl oil] in the pan and cook the ginger and garlic until fragrant.
# Pour in [14 oz coconut milk], soy sauce mixture. Simmer, stirring frequently until the sauce reduces and its color deepens. It should coat a spoon. 
# Add tofu and cashews to the pan and combine.
# Toss the snap peas with [1 tbl rice vinegar], scallions, mint and 1/2 tsp red pepper flakes. 
# Serve tofu with snap peas and rice. 
