TITLE crispy braised chicken thighs with olives, lemon, and fennel

# [3 cup fennel]
[12 item chicken thighs]
[1 cup [coarsely chopped] onion]
[1 tbl [finely chopped] garlic]
[1/4 cup dry white wine]
[1 cup green olives]
[1/4 tsp red pepper flakes]
[2 item bay leaves]
[4 item strips lemon zest]
[8 item thyme sprigs]
[1 cup chicken stock]

# Olives, here big fleshy green Ascolanes from Italy, and fennel are an extraordinary pairing with chicken. In this one-pot dish, we use only the thighs, the most flavorful part of the chicken.
# The seared chicken is braised in chicken stock on a bed of fennel, onion, and garlic, with strips of lemon zest. The stock picks up the lemon and fennel flavors and becomes concentrated and rich. Here the flavors are Mediterranean, but the technique itself can be taken in any number of seasoning directions.
# Cut off the fennel stalks. Trim the bottom of the bulbs and peel back the Layers until you reach the core; reserve the core for another use. Discard any bruised layers, and cut the fennel into 2-by-1/2-inch batons. You need 3 cups fennel for this recipe; reserve any remaining fennel for another use.


# Preheat the oven to 375F. Set a cooling rack on a baking sheet.
# Seshen the chicken thighs on both side with salt. Heat some canola oil in a large ovenproof saute pan or roset. pan that will hold all the this in one layer over medium-high heat. Add the thighs skin- side. down and brown on the skin side, about 4 minutes. Turn the thiehe over and cook for about I minute to sear the meat. Transfer to the cooling rack.
for 1.5 minutes. Add the garlic and cook for 1 minute. Cook, stirring ping tete he to medium to cod or minute. Cok and coe
often, until the onion is translucent, about 5 minutes. Stir in the fennel. ture the heat up to medium, and cook, stirring often, until the fennel ia crisp-tender, about 10 minutes.
# Pour in the wine and simmer for about 2 minutes to burn off the alcohol. Stir in the olives, red pepper flakes, bay leaves, lemon zest, and thyme, then pour in the chicken stock. Increase the heat, bring the liquid to a simmer, and cook until the fennel is tender, about 1 minute.
# Taste the stock and season with salt as needed. Return the chicken to the pan skin-side-up, in a single layer. When the liquid returns to a simmer, transfer to the oven and cook for about 20 minutes, until the chicken is cooked through.
# Turn on the broiler, and put the pan under the broiler for a minute or two to crisp and brown the chicken skin. Remove from the oven, and transfer to a serving platter. Garnish with the parsley leaves.