TITLE Duck Confit

{[Herb Salt]
# In a food processor combine: {
[1/2 cup salt]
[2 tbl light brown sugar]
[2 item bay leaf[, broken into pieces]]
[2 tbl [chopped] thyme]
[1/4 cup parsley leaves]
[1 tsp black peppercorns]
}
# Process until well combined. Set aside.
}

# Starting with [32 oz duck legs], pull away and discard any excess fat. 
# With scissors, trim the excess skin near the bottom of the legs and around the edges, leaving at least a quarter-inch overhang of skin.
* The correct ratio is 2 tablespoons of herb salt to 1 pound of duck legs. 
# Rub about $[herb salt], rubbing a little extra on the thicker parts and around the joint. 
# Put the legs flesh side up in a single layer in a baking dish. Cover with plastic wrap, and refrigerate for 24 hours.
# Rinse the legs under cold water and remove excess water.
# Vaccum pack the duck.
# Sous vide at 155F for 36 hours.  
# Cool and store until ready to serve.

# Remove from the refrigerator let sit to allow the fat to soften.
# Room the fat and any jellied juices.  
# Preheat the oven to 350F. Set a cooling rack over a baking sheet.
# Add some [duck fat] into a large frying pans and heat over high heat until very hot.
# Fry legs skin side down until the skin is richly browned.
# Move the duck legs to the cooling rack in the oven skin side up. 
# Heat through. 
