TITLE Glazed Lentil Walnut Apple Loaf

{[Balsamic Apple Glaze]
# Whisk together [1/4 cup ketchup], [1 tbl maple syrup], [2 tbl apple butter] and [2 tbl balsamic vinegar].
}

# Pick over and rinse [1 cup green lentils]. Add [3 cup water], season with [salt] Simmer, uncovered, at least 40 to 45 minutes, stirring frequently and adding a touch of water if needed; the goal is to slightly overcook them. Mash the lentils slightly with a spoon when ready.
# Preheat the oven to 325F. 
# Toast [1 cup pecans] at 325F for about 7 minutes; chop and set aside. 
# Increase the oven temperature to 350F.
# Whisk [3 tbl ground flax] with [1/2 cup water] in a small bowl and set aside.

# Saute [3 cloves garlic[, minced]] and [1.5 cup [diced] sweet onion] until softened; season with [salt]. 
# Add [1 cup [diced] celery], [1 cup [grated] carrot], [1/3 cup [peeled and grated] sweet apple] and [1/3 cup raisins], and sauté about 5 minutes more. Remove from the heat.

# In a large mixing bowl combine:{ [1/2 cup oat flour] [3/4 cup breadcrumbs] [2 tsp thyme] [pepper] [allepo] }
# Add the cooked lentils, toasted nuts, flax mixture and sauteed vegetables; mix.

# Grease a loaf pan and line it with parchment paper. 
# Press the mixture firmly into the pan. 
# Spread half of the $[Balsamic Apple Glaze] over the top of the loaf and reserve the rest as a dipping sauce.

# Bake at 350F for 40 to 50 minutes, uncovered, until the edges are lightly browned. 
# Cool in the pan at least 10 minutes before transferring to a cooling rack; wait until fully cool before slicing.
