TITLE Hummus Dinner Bowls With Spiced Ground Beef and Tomatoes

{[Quick Hummus]

# Place [28 oz chickpeas] in a medium pot and cover with water by one inch. 
# Bring to a boil over high heat, then reduce heat to medium-low and simmer, undisturbed, until chickpeas start falling apart, about 20 minutes. 
# Reserve [1 cup $[cooking liquid]], then drain chickpeas.
# Slip skins off of the chickpeas and discard.
# Transfer chickpeas to a food processor. Add [2 cloves garlic], [6 tbl lemon juice], [6 tbl tahini], [1.5 tsp kosher salt], and [2 tbl $[cooking liquid]].
# Process for a full 5 minutes until creamy and smooth. Add additional $[cooking liquid] to thin as needed.
# With the motor running, stream in [1/4 cup olive oil] and process until combined. 
# Transfer to a bowl and drizzle with [olive oil].

}

{[Garnish]
# In a bowl combine [2 cup [chopped] cherry tomato], [1 cup [chopped] parsley leaves], and [ 1 tbl lemon juice].
}
{[Spice Mix]
# In a small dish combine: [1 tsp coriander], [1/2 tsp pepper], [1/2 tsp cinnamon], and [1 tsp kosher salt].
}
# Preheat a heavy skillet and add [1 tbl vegetable oil]
# Pat beef dry and  press into an even layer in the skillet. 
# Sprinkle beef with $[spice mix] and cook, undisturbed, until a brown crust begins to form.
# Flip and break beef into pieces. Continue to cook until just cooked through.
# Spoon beef over $[Quick Hummus] and top with $[Garnish].
# Serve with [lemon wedges] and [aleppo pepper].

