
TITLE Impossible Pecan Pie

# Place [4 item large eggs] in a small bowl, cover with hot tap water and set aside.
# In a three quart stainless steel saucier combine [8 oz water], [21 oz sugar], and [1.5 tsp salt]. Using a medium heat, stir with a fork until the sugar dissolves and the syrup begins to bubble, about 7 minutes. 
# Fill a ramekin with water, then use it to wet a pastry brush and wipe all around the edges of the pot, wherever you see sugar crystals or splashes of syrup. Rewet the brush as needed, "washing" around the sides until totally clean. Be generous! Extra water will not hurt the pie filling, but sugar crystals will.
# Increase the heat to medium-high and clip on a digital thermometer. 
# Cook without stirring until the syrup is honey colored and 325F. Immediately remove from the heat, add [4 oz butter] all at once, and stir with a heat resistant spatula until the foam subsides. 
# Cool the syrup to 200°, about 10 minutes, stirring occasionally to ensure it cools at an even rate. 
# Preheat the oven to 350°
# In a large bowl wisk the eggs, [1 tsp vanilla], and [1 tbl bourbon] until combined.
# Fold [10 oz pecan halves] into the egg mixture. 
# Pour the hot butterscotch over the egg mixture, stir to combine
# Scrape into the prepared crust, and don't worry about trying to spread it into an even layer. 
# Bake 30 minutes, 
# Cover the outer ring of crust with a pie shield and continue baking until the filling is bubbling hot and all puffed, about 15 minutes more.
# When fully baked, the pie will registers 210° in the center. 
# Cool at least 2 hours before slicing. 

* Wrapped in plastic, leftovers will keep 3 days at room temperature, or a week inthe fridge.
* Yield: one 9° pie, 8 to 12 slices 
* Active time: about 30 minutes
