TITLE Leek Frittata
# Position a rack in the center of the oven and heat the oven to 350F.
#[3 item large leeks] (white and light-green parts only), halved lengthwise, sliced on the diagonal 1/2-inch thick, and rinsed
# Heat [2 tbl butter] and [1 tbl olive oil] in a 10-inch, ovenproof nonstick skillet over medium-high heat. When the butter has melted, add the $[leeks] and a generous pinch of [salt] and cook, stirring, until the leeks are tender and lightly browned, about 6 minutes. Transfer to a plate, spread in an even layer, and let cool briefly.
# In a large bowl, whisk the [8 item eggs] with [1 tsp salt] and several grinds of [pepper]. Add the leeks, [1 tsp thyme], and [3 oz goat cheese] crumbled, and and gently stir to combine.
# Wipe the skillet clean and heat the remaining [1 tbl butter] and [1 tbl olive oil] over medium-low heat. When the butter has melted, add the egg mixture and gently shake the pan to evenly distribute the leeks and cheese. Cook until the eggs begin to set around the edges, about 5 minutes. Gently shake the pan to be sure the frittata isn't sticking (if necessary, slide a spatula around the perimeter to release it).
# Transfer the pan to the oven and continue to cook until the frittata is set in the center, about 5 minutes. Remove from the oven and let sit for about 2 minutes. Carefully slide the frittata onto a serving plate, cut into wedges, and serve warm or at room temperature.

* https://www.finecooking.com/recipe/leek-and-goat-cheese-frittata
