TITLE Moroccan Lentil Meatballs with Roasted Red Pepper Sauce

{[Lentil Meatballs]
# Preheat oven to 350F.
# In the bowl of a food processor, combine: [1.5 cup cooked lentils], [3/4 cup breadcrumbs], [1/2 cup roughly chopped red onion], [1/4 cup fresh parsley leaves ], [1 item egg], [2 tbl tomato paste], [1 tsp soy sauce], [1/2 tbl [minced] garlic], [1 tsp dried oregano], [1 tsp smoked paprika], [1/2 tsp salt], [1/2 tsp black pepper].
# Pulse, mixing until combined, but not pureed, leaving a little texture. (The texture should be similar to dough. If it feels too wet to roll, mix in extra breadcrumbs.) Transfer mixture to a bowl and wipe the food processor clean.
# Use a medium cookie dough scoop to scoop out tablespoon amounts of lentil meatball mixture and roll into 18 balls. Place on a lined baking sheet.
# Bake for 20 minutes until lightly browned.
}
{[Roasted Red Pepper Sauce]
# Combine and puree until smooth: [12 oz jarred roasted red peppers], [1/4 cup extra-virgin olive oil], [2 tbl harissa (I use Mina brand)], [1/2 tbl minced fresh garlic], [1/2 tsp each kosher salt and black pepper].
}
# Serve $[Lentil Meatballs] with $[Roasted Red Pepper Sauce]. Garnish with fresh chopped parsley, if desired.
