TITLE Moroccan Lentil Meatballs with Roasted Red Pepper Sauce

# Preheat oven to 350F.	

{[Lentil Meatballs]

# In a small pot combine [1/2 cup red lentils] and [1.5 cup water]. Bring to a boil simmer 6 minutes. Drain.

# In the bowl of a food processor, combine:{[1.5 cup $[cooked lentils]] [3/4 cup breadcrumbs] [1/2 cup [roughly chopped] red onion] [1/4 cup parsley] [1 item egg] [2 tbl tomato paste] [1 tsp soy sauce] [1/2 tbl [minced] garlic] [1 tsp dried oregano] [1 tsp smoked paprika] [1/2 tsp salt] [1/2 tsp black pepper]}

# Pulse, mixing until combined, but not pureed, leaving a little texture. (The texture should be similar to dough. If it feels too wet to roll, mix in extra breadcrumbs.)

# Use a medium cookie dough scoop to scoop out tablespoon amounts of lentil meatball mixture and roll into 18 balls. Place on a lined baking sheet.
# Bake for 20 minutes until lightly browned.

}

{[Roasted Red Pepper Sauce]
# In a blender combine: {[12 oz roasted red peppers][1/4 cup olive oil] [1 tbl harissa] [1/2 tbl [minced] garlic]
 [1/2 tsp kosher salt] [1/2 tsp black pepper]}.
# Process until smooth.
}

# Serve $[Lentil Meatballs] with $[Roasted Red Pepper Sauce]. Garnish with chopped parsley, if desired.
