TITLE Moroccan Vegetable Stew

# Pour [2 tbl olive oil] into a small frying pan over medium-low heat. Add [3 cloves garlic] crushed, [1 tsp ground coriander], [1 tsp ground cumin], [0.5 tsp cayenne], [0.25 tsp ground cinnamon]. Cook, stirring often until fragrant, 1 to 2 minutes, being careful not to scorch the garlic. Scrape the mixture into a slow-cooker (at least 5 qt.).

# Add [5 cup vegetable or chicken broth], [4 item carrots] peeled and cut into 1/2-inch lengths, [2.5 cup peeled eggplant] diced, [2.5 cup zucchini] sliced, [2 cup cauliflower florets], [1 cup onion] diced, [29 oz stewed tomatoes], [15 oz garbanzo beans], [0.75 cup dried currants], [1 cup toasted almonds] chopped, and [0.5 tbl kosher salt]. Stir to combine.

# Cover slow-cooker and cook on high until vegetables are tender to bite and flavors are blended, 4 hours.

# Ladle about 3 cups of the vegetable mixture into a blender. Holding lid down with a towel and taking care to avoid steam, whirl until smooth. Return puree to slow-cooker and stir to blend. Ladle stew into a tureen or individual bowls.

* Yield: Makes 12 cups; 6 to 8 servings
LINK https://www.myrecipes.com/recipe/moroccan-vegetable-stew
