TITLE Pan-roasted chicken with sweet sausage and peppers

* Here a chicken is cut into pieces, seasoned, and cooked with sausages, then added to a stew of peppers that's seasoned and finished in the oven. This is a wonderfully satisfying dish with the robust flavors of the peppers and sausage.
# Make [Peperonata Rustica] 
# Cut [1 item chicken] into 8 pieces each: 2 legs, 2 thighs, 2 breast halves, and 2 wings. Pat dry with paper towels, or let air-dry. Season with [salt and pepper].
# Heat some [canola oil] in a large dutch oven over medium heat until hot. Add the chicken thighs and drumsticks. Skin side down, and cook for 3 minutes. 
# Add the [3 item sweet italian sausage] and cook until the chicken is golden and the sausage is browned and crisp. It won't be fully cooked. 
# Once the chicken is browned. Turn the pieces over and sear the other side for 1 minute. Transfer the individual pieces and the sausages to a plate.
# Place skin-side-down in the saute pan, and cook until the skin is crisp and golden and the chicken is almost cooked through, about 8 minutes. Transfer to a plate.
# Drain any remaining oil from the pan and return to the heat. Add the Peperonata Rustica  to the pan, bring to a simmer
# Add the chicken, tucking it into the peppers. Cut the sausages in half and nestle them in the pan.
# Transfer to the oven and cook until the chicken is cooked through
# Drizzle the chicken with [olive oil], sprinkle with [fleur de sel], and top with the [parsley leaves]. Serve directly from the pan.