TITLE Tuscan Peasant Soup with Rosemary and Pancetta

# Dice [6 oz pancetta] and shred [4 cup savoy cabbage].
# Heat [2 tbl olive oil] in a dutch oven over medium heat. When hot, add the pancetta and cook, stirring frequently, until quite shrunken, golden brown, and crisp. Remove the pan from the heat and with a slotted spoon or strainer carefully transfer the pancetta to a paper-towel-lined plate. Pour off and discard all but 2 Tbs. of the fat from the pan.
# Return the pot to medium-high heat and add the chopped cabbage. Cook the cabbage, stirring occasionally, until limp and browned around the edges. Remove the pot from the heat again and transfer the cabbage to another plate.
# Mince [2 tbl garlic] and [1 tbl rosemary]. Dice [2 cup onion] and [1.5 cup carrots]. Put the pot back over medium heat and add [2 tbl olive oil]. When the oil is hot, add the onions, carrots, and [1/2 tsp salt]. Cook, stirring occasionally, until the onions are softened and the vegetables are browned around the edges and beginning to stick to the bottom of the pan. Add another [1 tbl olive oil], the garlic, the rosemary, cook, stirring, until the garlic is fragrant. Add [28 oz diced tomatoes].
# Return the cabbage to the pan and add [8 cup chicken broth]. Stir well, bring a simmer. Cook for 15 minutes to infuse the broth with the flavor of the vegetables. Add [28 oz cannellini beans], bring back to a simmer.
# Remove the pan from the heat, stir in an additional [1 tsp fresh rosemary], and let rest a few minutes.
# Taste the soup and add [1 tbl lemon juice] and pepper to taste.
# Serve the soup hot, garnished with the reserved pancetta crisps, [1 cup Parmigiano], grated.
