TITLE Peruvian Chicken with Green Sauce

{[Sauce]
# Blend [3 item jalapeno] roughly chopped, [2 item bunch cilantro], [1 cloves garlic], [120 ml mayonnaise], [60 ml sour cream], [10 ml lime juice], [5 ml vinegar] until smooth
# With blender running stream in [30 ml olive oil]
# Season with [black pepper] and [salt]
# Transfer to a sealed container and refrigerate until ready to use.
* Sauce will be quite loose at this point, but will thicken as it sits.
}


{[Chicken]
# Spatchcock [1 item chicken]
# In a bowl, combine:{[15 g kosher salt] [15 g cumin] [15 g paprika] [2.5 g pepper] [3 cloves garlic[, minced]] [30 ml vinegar] [30 ml vegetable oil]}
# Spread mixture evenly over all surfaces of chicken.
# For added stability, run a metal or wooden skewer horizontally through chicken, entering through one thigh, going through both breast halves, and exiting through other thigh. Tuck wing tips behind back.
}
# Prepare grill with a two zone fire.
# Place chicken, skin side up, on cooler side of grill, with legs facing toward hotter side. Cover grill, with vents on lid open and aligned over chicken. Open bottom vents of grill. Cook until an instant-read thermometer inserted into thickest part of breast registers 110F (43C). Carefully flip chicken and place, skin side down, on hotter side of grill, with breasts pointed toward cooler side. Press down firmly with a wide, stiff spatula to ensure good contact between bird and grill grates. Cover and cook until skin is crisp and an instant-read thermometer inserted into thickest part of breast registers 145 to 150F (63 to 66C), about 10 minutes longer. If chicken threatens to burn before temperature is achieved, carefully slide to cooler side of grill, cover, and continue to cook until done. Do not leave the lid off for longer than it takes to check temperature, or chicken will burn.

# Transfer chicken to a cutting board and allow to rest for 5 to 10 minutes. Carve and serve with sauce.
