TITLE Slow Cooked Kale and Eggs

# Bring a large of salted water to a boil. 
# Strip the ribs from [2 lbs tuscan kale]. 
# Blanch the kale. Drain, cool, and squeeze out the extra water. Coarsely cope and set aside.
# Gently fry [4 oz pancetta] in a large dutch oven / pot until well rendered & crisp. Remove, drain, and set aside.
# Thinly slice [1 cup yellow onion].
# Add [2 tbl olive oil] to the pot. A [1 sprig rosemary] a [1/8 tsp red pepper flake]. Fry until fragrent.
# Add onion, [1/2 tsp salt], [2 cloves garlic [minced]]. Saute until soft and beginning to brown. Discard rosemary.
# Add [2 tbl olive oil], [1/4 tsp salt], and reserved kale. Cook on medium low; stiring every 5-10 minutes until kale is almost black and slightly crisp around the edges. 
# While the kale cooks tear [2 cup bread] into small cubes.
# Pre-heat a large skillet. Toast bread crumbs in [3 tbl olive oil] until well browned and crunchy. 
# When the kale is done fry [4 item eggs]. 
# Serve kale, with bread crumbs, reserved pancetta, and a fried egg.
    
