TITLE Spaghetti Squash Lasagna with Spinach

# Preheat oven to 350F.

# Prepare [3 lbs spaghetti squash]. Cut squash in half lengthwise and remove seeds. Place squash halves, cut sides down, on a baking sheet. Roast until tender, about 50 minutes. Scrape inside of squash with a fork to loosen strands. Place in a large bowl. 

# In a large skillet saute [4 cloves garlic[, thinly sliced]] and [baby spinach] it wilts. Add to bowl with the squash strands. 

# Add [8 oz ricotta cheese], [1/8 tsp kosher salt], and [1/4 cup mozzarella cheese] to the bowl stir to combine.

# Return skillet to medium-high heat. Saute [8 oz ground turkey] until browned, stirring to crumble.

# Add [ 1.5 cup marinara sauce] to the pan and simmer for 5 minutes.

# Preheat oven to 425F.

# Lightly oil a 9 x 13 baking dish. Spoon half of the sauce into the dish. Top evenly with squash mixture. Cover with remaining sauce.

# Sprinkle evenly with remaining [1/4 cup mozzarella cheese] cheese and [1 oz parmigiano]. 

# Bake for 25 minutes or until heated through and bubbling.
