TITLE Spaghetti Squash with Asparagus, Ricotta, Lemon, and Thyme

# Preheat to 375F.
# Cut a [1.5 lbs spaghetti squash] lengthwise and scrape out the seeds. Brush the cut sides with [1/2 tbl olive oil]. Place cut-side down on one half of a rimmed baking sheet. Roast for 35 minutes. 
# Trim [1 lbs asparagus] and cut the stalks on a diagonal into 2-inch pieces. Peel and smash [2 cloves garlic]. 
# Remove the baking sheet with the squash. Add the asparagus to one side and toss with [1/2 tbl olive oil]. Place a garlic clove beneath each squash half. Return the baking sheet to the oven and roast until the asparagus is tender and starting to char, and the squash is easily pierced with a fork, about 10 minutes.
# In a large bowl combine:{ [3/4 cup ricotta] [1 tsp lemon zest] [3 tbl lemon juice] [1 tsp thyme] [1/2 tsp salt] [1/4 tsp pepper]} 
# Toast [pine nuts] for garnish.
# Remove the baking sheet from the oven and carefully remove the garlic cloves from beneath the squash. Add to the ricotta and mix well. 
# Add the asparagus to the bowl.
# When the squash is cool enough to handle but still warm, run a fork through the flesh to separate and remove the strands from the shell. Add to the ricotta mixture and stir to combine. 
# Garnish with pine nuts.