TITLE Spice Beef and Hummus

{ [Hummus]
# Place [28 oz chickpeas] in a medium pot and cover with water. Bring to a boil over high heat, then reduce simmer, undisturbed, until chickpeas start falling apart, about 30 minutes.
# Rinse chickpeas by refilling the pot with cold water. Agitate gently and discard any skins that float to the surface. Drain.
# Transfer chickpeas to a food processor. 
# Add [2 cloves garlic], [6 tbl lemon juice], [6 tbl tahini], [1.5 tsp salt], and [2 tbl water].
# Process until creamy and smooth. Thin with additional [lemon juice] and [water] as needed.
# Stir in [1/4 cup olive oil]
# Transfer to a medium bowl and drizzle with more oil.
}

{[Garnish]
# In a medium bowl combine, [2 cup cherry tomatoes[, halved]], [1 cup parsley[, chopped]], and [1 tbl lemon juice]. 
}

{[Spiced Beef]
# Pat [1 lbs ground beef] dry. 
# In a small bowl combine [1/2 tsp pepper], [1/2 tsp cinnamon], and [1 tsp salt].
# Heat a large skillet over high heat. Then press beef into an even layer in skillet.
# Sprinkle beef with spice mixture. 
# Cook, undisturbed, until a crust begins to form. 
# Flip the beef and break into pieces. Continue cooking until just cooked through.
}

#  Divide $[hummus] among shallow bowls. Create a wide divot in the center. Spoon $[spiced beef] and $[garnish] over the $[hummus]
# Drizzle with [olive oil] and sprinkle with [Aleppo pepper]