TITLE Spicy Braised Tofu

# Press [ 14 oz extra firm tofu].
# Make [rice] for serving.
# Slice tofu in half lengthwise, then cut crosswise into 6 sections to create 12 squares.
# Whisk [3 tbl soy sauce], [3 tbl mirin], [1 tsp sesame oil], [3/4 tsp gochugaru], and [3 tbl water] in a small bowl.
# Trim the dark green top from [1 item scallion].  Thinly slice remaining white and pale green parts of scallion. 
# Heat [1 tbl oil] in a nonstick skillet over medium-high. Carefully add tofu in a single layer and lightly season with [salt]. 
# Cook, undisturbed, until golden brown; turn over and cook until golden brown on other side. Transfer tofu to a plate.
# Heat remaining [1 tbl oil] in the skillet over medium heat. 
# Cook scallion, [1 cloves [minced] garlic], and [1 tsp [finely chopped] ginger], stirring, until softened.
# Return tofu to skillet. Pour in sauce and bring to a simmer. 
# Reduce heat to medium-low and cook, turning tofu occasionally and spooning sauce over, until sauce is reduced by about half.
# Sprinkle with [toasted sesame seeds] and [1 item scallion, [thinly sliced]].