TITLE Vegetarian Shepherd's Pie

{[Mashed Potato Topping]
* Time this to boil while you make the filling so the potatoes stay warm.
# Place [2 lbs russet [, peeled and chopped]] in a large pot and add enough water to cover. Bring to a low boil and cook until soft. Drain and set aside. 
# Place the warm potatoes in a large bowl. Add [3 tbl butter], [1/4 cup sour cream] and [1/2 tsp salt]. Mash until creamy. 
# Fold in [3/4 cup [shredded] cheddar].
}

# Dice [1 cup onion], [1 cup carrots], [1/2 cup celery]. Slice [8 oz mushrooms].
# Saute veg until they begin soften
# Add [3 cloves garlic[, minced]] and cook until fragrant. 
# Add [1/2 cup red wine] and [1 tsp red wine vinegar]. Stir and scrape up any fond. 
# Cook until most of the liquid has evaporated.
# Add [3 tbl tomato paste], [2 cup vegetable broth], [15 oz canalini beans]], [2 tsp [chopped] thyme] [2 tsp [chopped] rosemary], [1/2 tsp salt], [1/4 tsp black pepper], [1 item bay leaf].
# Simmer, stirring occasionally, until the liquid has reduced and thickened into a sauce.
# Remove from the heat. Discard the bay leaf, then stir in [1.5 cup [frozen corn].
# Preheat the oven to 350F. 
# Spread the $[Mashed Potato Topping] evenly over the filling.
# Bake for 30 minutes. 
# Turn on the broiler, and broil until golden spots appear on the topping.
