TITLE White Chicken Chili

# Soak [1 lbs dried cannellini beans] overnight in salted water.
# Set an oven rack 8 inches below the broiler. Preheat.
# On a large foil lined baking sheet, rub [2 item poblano chiles], [4 item Anaheim], [2 item jalapeno], [8 cloves garlic], and [1 item onion[, peeled and halved]] in [oil] and [salt] lightly. 
# Broil turning occasionally until skins are blacked and wrinkled. Roughly 15 to 20 minutes.
# Gather up the foil to form a pouch and let the blackened veg steam to losen skins.
# Peel and seed the peppers. 
# Add all veg to a blender. Blend until smooth. 
# In a large dutch oven heat [2 tbl oil] until shimmering. 
# Add [1 tbl cumin] and [1 tsp coriander]. Bloom. 
# Add blended chili puree. Rinse blender with [4 cup chicken stock] and add to the pot. 
# Drain and rinse the beans. Add to the pot. 
# Add [2 lbs boneless skinless chicken breast] to the pot. Bring to a simmer. 
# When the chicken reaches 150F remove it from the pot and set aside. 
# Continue to cook the beans until they are tender. Approximately one hour.
# Remove 1.5 cups of the beans and liquid and blend until smooth return to the pot.   
# Shred the chicken into bite size pieces and return to the pot to warm through. 
# Stir in [8 oz [shredded] jack cheese], [1/2 cup [chopped] cilantro], [2 tbl lime juice]. 
# Service with additional cheese, cilantro, lime, and [scallions], white and light green parts only, thinly sliced